-dontwarn okhttp3.**
-dontwarn okio.**
-keep class okhttp3.** { *; }
-keep class com.google.mlkit.** { *; }
-keep class dev.otpilot.model.** { *; }
-keep class dev.otpilot.crypto.CryptoUtil$EncryptedPayload { *; }
